apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  namespace: eks-sample-app
  labels:
    app: eks-ghost-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-ghost-app
  template:
    metadata:
      labels:
        app: eks-ghost-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: nordcloud-ghost
          image: 176181560477.dkr.ecr.eu-west-1.amazonaws.com/nordcloud-ghost:latest
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux